=== LoganAMorrison/blackthorn/blackthorn/constraints/experiment_data/fermi_schema.json
{
  "$schema": "http://json-schema.org/schema",
  "title": "Schema for Fermi observation data of Dwarf Spheroidal Galaxies",
  "type": "object",
  "properties": {
    "galaxyName": {
      "type": "string",
      "description": "Name of the galaxy"
    },
    "id": {
      "type": "string",
      "description": "Identifier of the galaxy"
    },
    "galacticLongitude": {
      "type": "number",
      "description": "Longitude of the galaxy",
      "units": ["deg"]
    },
    "galacticLatitude": {
      "type": "number",
      "description": "Latitude of the galaxy",
      "units": ["deg"]
    },
    "angularSize": {
      "type": "number",
      "description": "Angular size of observation area",
      "units": ["sr"]
    },
    "distance": {
      "type": "number",
      "description": "Distance from Earth to the target",
      "units": ["kpc"]
    },
    "observedJFactor": {
      "type": "object",
      "description": "Observed value of the J-factor",
      "properties": {
        "mean": {
          "type": "number",
          "description": "Mean of the observation",
          "units": ["GeV^2 cm^-5"]
        },
        "uncertainty": {
          "type": "number",
          "description": "Uncertainty of the observation",
          "units": ["GeV^2 cm^-5"]
        }
      }
    },
    "data": {
      "type": "array",
      "description": "Upper limits and likelihoods from the Fermi collaboration",
      "items": {
        "type": "object",
        "properties": {
          "lowerEnergy": {
            "type": "number",
            "description": "Lower energy value of the bin"
          },
          "upperEnergy": {
            "type": "number",
            "description": "Upper energy value of the bin"
          },
          "fluxUpperLimit": {
            "type": "number",
            "description": "Upper limit on the total flux"
          },
          "differentialFluxUpperLimit": {
            "type": "number",
            "description": "Upper limit on the differential flux"
          },
          "fluxLikelihoods": {
            "type": "array",
            "description": "List of the fluxes and their corresponding likelihoods",
            "items": {
              "type": "object",
              "properties": {
                "flux": {
                  "type": "number",
                  "description": "Value of the flux"
                },
                "deltaLogLikelihood": {
                  "type": "number",
                  "description": "Log-likelihood of the flux"
                }
              }
            }
          }
        }
      }
    }
  }
}

=== LoganAMorrison/blackthorn/blackthorn/constraints/experiment_data/coma_berenices.json
{
  "id": "coma_berenices",
  "galaxyName": "Coma Berenices",
  "galacticLongitude": 241.9,
  "galacticLatitude": 83.6,
  "angularSize": 0.00025,
  "distance": 44,
  "observedJFactor": {
    "mean": 1e+19,
    "uncertainty": 5.756462732485115e+18
  },
  "data": [
    {
      "lowerEnergy": 500.0,
      "upperEnergy": 666.760716,
      "fluxUpperLimit": 8.191e-08,
      "differentialFluxUpperLimit": 2.8459e-07,
      "fluxLikelihoods": [
        {
          "flux": 0.0,
          "deltaLogLikelihood": 0.0074801634
        },
        {
          "flux": 1.76749387e-10,
          "deltaLogLikelihood": 0.00627853981
        },
        {
          "flux": 3.14309796e-10,
          "deltaLogLikelihood": 0.00533735285
        },
        {
          "flux": 5.58930639e-10,
          "deltaLogLikelihood": 0.00365072781
        },
        {
          "flux": 9.93934847e-10,
          "deltaLogLikelihood": 0.000610618419
        },
        {
          "flux": 1.76749387e-09,
          "deltaLogLikelihood": -0.00492420852
        },
        {
          "flux": 3.14309796e-09,
          "deltaLogLikelihood": -0.0151712223
        },
        {
          "flux": 5.58930639e-09,
          "deltaLogLikelihood": -0.034659731
        },
        {
          "flux": 9.93934847e-09,
          "deltaLogLikelihood": -0.0732507496
        },
        {
          "flux": 1.76749387e-08,
          "deltaLogLikelihood": -0.153948091
        },
        {
          "flux": 3.14309796e-08,
          "deltaLogLikelihood": -0.333720991
        },
        {
          "flux": 5.58930639e-08,
          "deltaLogLikelihood": -0.758937234
        },
        {
          "flux": 9.93934847e-08,
          "deltaLogLikelihood": -1.80844959
        },
        {
          "flux": 1.76749387e-07,
          "deltaLogLikelihood": -4.44467725
        },
        {
          "flux": 3.14309796e-07,
          "deltaLogLikelihood": -11.028692
        },
        {
          "flux": 5.58930639e-07,
          "deltaLogLikelihood": -27.1208971
        },
        {
          "flux": 9.93934847e-07,
          "deltaLogLikelihood": -65.2800221
        },
        {
          "flux": 1.76749387e-06,
          "deltaLogLikelihood": -152.730383
        },
        {
          "flux": 3.14309796e-06,
          "deltaLogLikelihood": -346.270744
        },
        {
          "flux": 5.58930639e-06,
          "deltaLogLikelihood": -760.418052
        },
        {
          "flux": 9.93934847e-06,
          "deltaLogLikelihood": -1619.19223
        },
        {
          "flux": 1.76749387e-05,
          "deltaLogLikelihood": -3349.5716
        },
        {
          "flux": 3.14309796e-05,
          "deltaLogLikelihood": -6748.36916
        },
        {
          "flux": 5.58930639e-05,
          "deltaLogLikelihood": -13278.9163
        },
        {
          "flux": 9.93934847e-05,
          "deltaLogLikelihood": -25597.5608
        }
      ]
    },
    {
      "lowerEnergy": 666.760716,
      "upperEnergy": 889.139705,
      "fluxUpperLimit": 4.675e-08,
      "differentialFluxUpperLimit": 1.6243e-07,
      "fluxLikelihoods": [
        {
          "flux": 0.0,
          "deltaLogLikelihood": 5.90080163e-09
        },
        {
          "flux": 1.76749387e-10,
          "deltaLogLikelihood": -0.0036394979
        },
        {
          "flux": 3.14309796e-10,
          "deltaLogLikelihood": -0.00648120233
        },
        {
          "flux": 5.58930639e-10,
          "deltaLogLikelihood": -0.0115542923
        },
        {
          "flux": 9.93934847e-10,
          "deltaLogLikelihood": -0.0206378883
        },
        {
          "flux": 1.76749387e-09,
          "deltaLogLikelihood": -0.0369866281
        },
        {
          "flux": 3.14309796e-09,
          "deltaLogLikelihood": -0.066671049
        },
        {
          "flux": 5.58930639e-09,
          "deltaLogLikelihood": -0.121356676
        },
        {
          "flux": 9.93934847e-09,
          "deltaLogLikelihood": -0.224413405
        },
        {
          "flux": 1.76749387e-08,
          "deltaLogLikelihood": -0.425061976
        },
        {
          "flux": 3.14309796e-08,
          "deltaLogLikelihood": -0.83207613
        },
        {
          "flux": 5.58930639e-08,
          "deltaLogLikelihood": -1.6936114
        },
        {
          "flux": 9.93934847e-08,
          "deltaLogLikelihood": -3.57947263
        },
        {
          "flux": 1.76749387e-07,
          "deltaLogLikelihood": -7.77742157
        },
        {
          "flux": 3.14309796e-07,
          "deltaLogLikelihood": -17.1231393
        },
        {
          "flux": 5.58930639e-07,
          "deltaLogLikelihood": -37.7043462
        },
        {
          "flux": 9.93934847e-07,
          "deltaLogLikelihood": -82.2984178
        },
        {
          "flux": 1.76749387e-06,
          "deltaLogLikelihood": -177.113838
        },
        {
          "flux": 3.14309796e-06,
          "deltaLogLikelihood": -374.568272
        },
        {
          "flux": 5.58930639e-06,
          "deltaLogLikelihood": -776.813573
        },
        {
          "flux": 9.93934847e-06,
          "deltaLogLikelihood": -1578.25444
        },
        {
          "flux": 1.76749387e-05,
          "deltaLogLikelihood": -3141.69455
        },
        {
          "flux": 3.14309796e-05,
          "deltaLogLikelihood": -6134.13439
        },
        {
          "flux": 5.58930639e-05,
          "deltaLogLikelihood": -11768.4813
        },
        {
          "flux": 9.93934847e-05,
          "deltaLogLikelihood": -22233.3475
        }
      ]
    },
    {
      "lowerEnergy": 889.139705,
      "upperEnergy": 1185.68685,
      "fluxUpperLimit": 6.8938e-08,
      "differentialFluxUpperLimit": 2.3951e-07,
      "fluxLikelihoods": [
        {
          "flux": 0.0,
          "deltaLogLikelihood": 0.00357447335
        },
        {
          "flux": 1.76749387e-10,
          "deltaLogLikelihood": 0.00216829474
        },
        {
          "flux": 3.14309796e-10,
          "deltaLogLikelihood": 0.00106501427
        },
        {
          "flux": 5.58930639e-10,
          "deltaLogLikelihood": -0.000916093672
        },
        {
          "flux": 9.93934847e-10,
          "deltaLogLikelihood": -0.00449950552
        },
        {
          "flux": 1.76749387e-09,
          "deltaLogLikelihood": -0.0110620584
        },
        {
          "flux": 3.14309796e-09,
          "deltaLogLikelihood": -0.0233286738
        },
        {
          "flux": 5.58930639e-09,
          "deltaLogLikelihood": -0.0470009148
        },
        {
          "flux": 9.93934847e-09,
          "deltaLogLikelihood": -0.0948250023
        },
        {
          "flux": 1.76749387e-08,
          "deltaLogLikelihood": -0.197198691
        },
        {
          "flux": 3.14309796e-08,
          "deltaLogLikelihood": -0.430122889
        },
        {
          "flux": 5.58930639e-08,
          "deltaLogLikelihood": -0.9870047
        },
        {
          "flux": 9.93934847e-08,
          "deltaLogLikelihood": -2.35261182
        },
        {
          "flux": 1.76749387e-07,
          "deltaLogLikelihood": -5.69253847
        },
        {
          "flux": 3.14309796e-07,
          "deltaLogLikelihood": -13.6605553
        },
        {
          "flux": 5.58930639e-07,
          "deltaLogLikelihood": -31.9830741
        },
        {
          "flux": 9.93934847e-07,
          "deltaLogLikelihood": -72.4808461
        },
        {
          "flux": 1.76749387e-06,
          "deltaLogLikelihood": -158.747835
        },
        {
          "flux": 3.14309796e-06,
          "deltaLogLikelihood": -336.679221
        },
        {
          "flux": 5.58930639e-06,
          "deltaLogLikelihood": -693.678246
        },
        {
          "flux": 9.93934847e-06,
          "deltaLogLikelihood": -1393.18399
        },
        {
          "flux": 1.76749387e-05,
          "deltaLogLikelihood": -2736.17346
        },
        {
          "flux": 3.14309796e-05,
          "deltaLogLikelihood": -5270.42528
        },
        {
          "flux": 5.58930639e-05,
          "deltaLogLikelihood": -9984.80487
        },
        {
          "flux": 9.93934847e-05,
          "deltaLogLikelihood": -18654.9657
        }
      ]
    },
    {
      "lowerEnergy": 1185.68685,
      "upperEnergy": 1581.13883,
      "fluxUpperLimit": 1.0533e-07,
      "differentialFluxUpperLimit": 3.66e-07,
      "fluxLikelihoods": [
        {
          "flux": 0.0,
          "deltaLogLikelihood": -0.225402181
        },
        {
          "flux": 1.76749387e-10,
          "deltaLogLikelihood": -0.221977686
        },
        {
          "flux": 3.14309796e-10,
          "deltaLogLikelihood": -0.219334077
        },
        {
          "flux": 5.58930639e-10,
          "deltaLogLikelihood": -0.214679488
        },
        {
          "flux": 9.93934847e-10,
          "deltaLogLikelihood": -0.206548285
        },
        {
          "flux": 1.76749387e-09,
          "deltaLogLikelihood": -0.192544506
        },
        {
          "flux": 3.14309796e-09,
          "deltaLogLikelihood": -0.169051733
        },
        {
          "flux": 5.58930639e-09,
          "deltaLogLikelihood": -0.13156671
        },
        {
          "flux": 9.93934847e-09,
          "deltaLogLikelihood": -0.0776312981
        },
        {
          "flux": 1.76749387e-08,
          "deltaLogLikelihood": -0.0179137183
        },
        {
          "flux": 3.14309796e-08,
          "deltaLogLikelihood": -0.00873016432
        },
        {
          "flux": 5.58930639e-08,
          "deltaLogLikelihood": -0.233240113
        },
        {
          "flux": 9.93934847e-08,
          "deltaLogLikelihood": -1.18158502
        },
        {
          "flux": 1.76749387e-07,
          "deltaLogLikelihood": -4.02216522
        },
        {
          "flux": 3.14309796e-07,
          "deltaLogLikelihood": -11.3337008
        },
        {
